### ISSUE TITLE
QR code not being created

### ISSUE THREAD

**Issue by nickdring** [joshp23/YOURLS-IQRCodes#16]
We've configured the plugin and the qr code created has a broken link as you can see here,.
![screen shot 2017-07-07 at 13 42 38](https://user-images.githubusercontent.com/2345452/27956996-90262232-631c-11e7-849e-7e3747902a51.png)
Also when we upload the logo it doesn't seem to get saved.

**Comment by joshp23** [comment]
If no qr codes are being generated then you may want to check permissions for the cache location. This may be the reason your logo isn't being saved as well.

Always start by checking permissions.

Open a separate issue for your second issue, please.

**Comment by bm1-phillip** [comment]
Hello, I get the same error. The users/cache/ folder does not exist either.
Can it be at the SymLink?

I think it's not true.
```
ln -s user/plugins/iqrcodes/assets/srv.php pages/srv.php
ln -s user/plugins/iqrcodes/assets/qrchk.php pages/qrchk.php
```

**Comment by nickdring** [comment]
HI, no the permissions seem ok, indeed inside the cache folder we can see files. The cache folder we created ourselves.
![screen_thumb](https://user-images.githubusercontent.com/2345452/28009056-47fd9644-655a-11e7-8338-bd831e5a85e4.png)

**Comment by nickdring** [comment]
[cache.zip](https://github.com/joshp23/YOURLS-IQRCodes/files/1134926/cache.zip)
here are the contents of the zip file

**Comment by joshp23** [comment]
There needs to be two folders called cache (from YOURLS root)
-  `user/plugins/iqrcodes/cache`
-  `user/cache/qr`

The first (that you zipped above) is a static tool-box for phpqrcodes.php, it allows for slightly faster qr code image generation. The second is where iqrcodes will store the generated qr code images _and_ your logo file. 

Again, the issues mentioned in this particular thread _all_ stem from a simple permissions issue. Iqrcodes plugin is trying to create `user/cache/qr` but apparently doesn't have the necessary permissions to write to the `user` directory in both of your setups. This is fine. You can do something like this:
-  chown -R www-data:www-data /PATH/TO/YOURLS

Or, in case that is either unacceptable to you, or still doesn't do the trick, just do the following from YOURLS root:
-  mkdir user/cache/qr
-  chown -R www-data:www-data user/cache
-  chmod -R 777 user/cache

The third command is merely for good measure, and shouldn't be required.
