### ISSUE TITLE
Not working when YOURLS is installed in subdirectory

### ISSUE THREAD

**Issue by candlewickpress** [joshp23/YOURLS-IQRCodes#18]
My YOURLS installation lives in a /r/ directory on my website root. It seems like iQRCodes makes calls to DOCUMENT_ROOT to determine path, so it fails.

I tried changing the calls to point to this /r/ directory by tweaking the plugin.php and other included files, and while it seems to have fixed the 404 errors I was getting in the browser (CSS, JS files, etc), it still doesn't seem to allow the QR code generation.

Is there a way to allow this to run in a subdirectory? Would using YOURLS_ABSPATH instead of DOCUMENT_ROOT allow this to work?

**Comment by joshp23** [comment]
Good call. I don't see why your solution wouldn't work.

Feel free to test and pull request if it works. If not... I should have some time on my hands over the next few days to look at this.

**Comment by joshp23** [comment]
This has been addressed. Thanks for the heads up.
