### ISSUE TITLE
.png-errors.txt entry on every call of admin interface

### ISSUE THREAD

**Issue by MarcJanssen** [joshp23/YOURLS-IQRCodes#2]
I just notice that every time I access the admin interface a new entry(line) is attached to qrc_d41d8cd98f00b204e9800998ecf8427e.png-errors.txt inside plugin directory.
This happens after a clean database/installation, too.
The line added is always the same (the timestamp matches the admin interfaces access time):
2017-02-27 12:36:16: empty string!!!

I did not notice any error while using the plugin. But the file will grow with every acess to admin interface.

**Comment by joshp23** [comment]
I have the same issue. not sure why. I'll debug this when I have time.

**Comment by joshp23** [comment]
this may have been fixed with one of the recent merges.

**Comment by joshp23** [comment]
I think that this has something to do with the javascript call on the admin page load. However, I'm not sure how to fix it yet. I thought that #12 would have fixed it, but it still seems to happen. It looks like might be related to #13

**Comment by joshp23** [comment]
#13 has been fixed, this irksome issue remains.

**Comment by joshp23** [comment]
Also, it's odd that I am getting the exact same file name...

**Comment by joshp23** [comment]
`d41d8cd98f00b204e9800998ecf8427e` is the resulting md5 hash of an empty string

**Comment by joshp23** [comment]
Found Bug: When the admin page loads,

 `yourls_add_filter( 'share_box_data', 'iqrcodes_sharebox' );`  on line 343 of plugin.php

is triggered. Apparently the share box is loaded, but not exposed, causing 

```	
if ( !file_exists( $filepath ) )
		QRcode::png( $shorturl, $filepath, $opt[1], $opt[2], $opt[3] );
```
to fire, but with an emty string where $shorturl should be.

**Comment by joshp23** [comment]
Happy to say that this is finally [fixed](https://github.com/joshp23/YOURLS-IQRCodes/commit/c7553a64ada51a573fa6bfac98908a7b7c3ba166) in the latest [release](https://github.com/joshp23/YOURLS-IQRCodes/releases/latest) (>=1.1.4).
