### ISSUE TITLE
Logo watermark is not generated on QR code

### ISSUE THREAD

**Issue by josedsilva** [joshp23/YOURLS-IQRCodes#23]
Logo watermark is not generated on QR code even if setup in the admin -> "IQRCodes Config" section.

**Comment by joshp23** [comment]
confirmed. let me do some debugging.

**Comment by joshp23** [comment]
Pretty sure I found it. Looks like line 924 of `iqrcodes/assets/phpqrcode.php` needs to be updated from this:

`$logoPath = $_SERVER['DOCUMENT_ROOT']."/user/plugins/iqrcodes/logo.".$opt[5];`

to this:

`$logoPath = YOURLS_ABSPATH."/".$opt[0]."/logo.".$opt[5];`

If you would like to test this and send a merge request that would be peachy, if not I will potentially get to it sometime tomorrow. Thanks for pointing this out.

**Comment by josedsilva** [comment]
This fixes the path issue. But now, only a PNG logo watermark can be used.
If the logo is a JPG, it does not show on the QR code.

**Comment by joshp23** [comment]
H'm, I bet if `Image Type` for qrcode output was set to JPG then it would work with a JPG based logo. I think changing 924 to

`$logoPath = YOURLS_ABSPATH."/".$opt[0]."/logo.*";` <<---**EDIT**: this does not work

might do the trick in the meantime. However, I will prefer to explicitly set the logo file type here.

**Comment by joshp23** [comment]
fixed, with many other logo related bug fixes, with latest commit.
