### ISSUE TITLE
Not quite working

### ISSUE THREAD

**Issue by LymeSimon** [joshp23/YOURLS-IQRCodes#26]
Followed the installation instructions and got:

Uncaught Error: Call to undefined method ezSQL_pdo_YOURLS::fetchObjects() in /var/www/**mydomain**/user/plugins/iqrcodes/plugin.php:597

Running YOURLS v 1.7.2

Anyone got this plugin running with that version?

**Comment by joshp23** [comment]
Nobody has this plugin working with that version.

**Comment by joshp23** [comment]
1.4.8 of this plugin and onward requires 1.7.3 YOURLS. I thought it was in the README. I'll update it soon. Just update YOURLS from git and you're good to go.

**Comment by joshp23** [comment]
for brevity, I'll consider making this backwards compatible in the future, but I cannot promise when.

**Comment by joshp23** [comment]
Ok, Try it now :) I just made this backwards compatible with 1.7.2. Easier than I thought. Please let me know how this worked, or just close this issue when you confirm that it's working.

**Comment by LymeSimon** [comment]
The code now generates the QRCode images and I don't get anything in my error log but no QR codes delivered from the admin URLs. For example,

https://moxp.uk/srv/?id=iqrcodes&key=9ada5c024108cc4c72718aa2a7810811&fn=qrc_a9149d4b4d152b46739d5cdf445dce85.png

delivers nothing (gets redirected to "Magic Oxygen YOURLS URL shortener, This is a private URL shortener." but

https://moxp.uk/user/cache/qr/qrc_a9149d4b4d152b46739d5cdf445dce85.png
delivers the correct png image for the URL

Is this a step that I have missed or got wrong, or because it's a private shortener? I used symbolic links for srv.php and qrchk.php and my apache conf has:
Options Indexes FollowSymLinks MultiViews

This is so close, I'm quite excited to get it working!

Cheers
Simon West

**Comment by joshp23** [comment]
well, keys are only good for a short period of time, anyway, so there's that. not sure why that would be happening with a valid key, etc. What do the logs say?

**Comment by joshp23** [comment]
I just noticed that your srv/ linked qrcode url responds with `This is a private URL shortener.` which leads me to believe that there is a problem with permissions or the srv link itself. did you copy srv.php or link it to `YOURLS/pages/` ?

**Comment by LymeSimon** [comment]
The file was linked and .htaccess configured to follow links... I unlinked and copied, and lo and behold, it bloomin' well works. Thanks for the hint on what the issue was.

**Comment by joshp23** [comment]
glad it worked. curious why your links didn't work, however...
