### ISSUE TITLE
No logo on file

### ISSUE THREAD

**Issue by Andyt8** [joshp23/YOURLS-IQRCodes#27]
Hello,

Today I installed your plugin and did an upgrade from original QRCodes. It work without any problems execpt of logo generation.

I uploaded a 64x64 pixel picture (png) and qrcode (png) is still without Logo. I read in blue letters: No logo on file. The option "Use Logo?" is set to yes. Scaling is at the moment 0.5, but tried 1 or 0.25.

In the cache folder, I see a logo.png picture and of course the qrc_*.png files.

Are there any mistakes by me or is this maybe a bug? Please for help.

regards, Andyt

**Comment by joshp23** [comment]
I'll look into this when I have time. I take it there was nothing in your logs?

**Comment by Andyt8** [comment]
Thank you for your response.

At the moment I didn't find any new information in the log file. I will check if all logging information are enabled and give response if I found new information.

**Comment by joshp23** [comment]
Fixed with de5404aabddf9d3ed50b71ed21ba163455fd9e3a
Please update to latest
