### ISSUE TITLE
Feature request .qr after short url

### ISSUE THREAD

**Issue by Andyt8** [joshp23/YOURLS-IQRCodes#28]
Hello,

This is not a real issue, but I want to ask if it is possible to send a feature request?

Is it possible to extend the plugin to support the ".qr" as extension to a shorturl which will display the QR Code of the shorturl form file system?

regards Andyt

**Comment by joshp23** [comment]
sure. when I have time. likely not until at least this weekend. or two weeks after that.

**Comment by joshp23** [comment]
added with 10f640e382e56791a3abed3e25bb1841a52289cd
