### ISSUE TITLE
Short link QR code is not displayed

### ISSUE THREAD

**Issue by z886** [joshp23/YOURLS-IQRCodes#29]
Hi,
   After creating a short link, the QR code is not displayed, and it cannot be displayed on the sharing page, but the QR code is generated in the cache folder. Please help me, thank you!
![aa](https://user-images.githubusercontent.com/2437974/57920263-39829a00-78cd-11e9-920a-9ccc0e0693b6.png)

**Comment by joshp23** [comment]
With no information besides, "It's not working as expected," there's not a lot I can do. Please look to your log files for some kind of error. Check permissions of usrv.php and qrcheck.php. Perhaps copy those files instead of linking. Just shots in the dark.

**Comment by z886** [comment]
Hi,
I have found the reason and conflict with this plugin (Allow Forward Slashes in Short URLs). When this Allow Forward Slashes in Short URLs is activated, it will cause the QR code to display broken images. Can you solve the problem? Thank you!

**Comment by joshp23** [comment]
I can look at this when I have time. However, more info, such as specific error messages and debug info from YOURLS would certainly help.

**Comment by joshp23** [comment]
Please update U-SRV with the [latest](https://github.com/joshp23/YOURLS-U-SRV/releases/latest) release and close this issue if resolved.

**Comment by z886** [comment]
The compatibility issue has been resolved, thank you very much!
