### ISSUE TITLE
The QR code generated by the IQRCodes plugin of the second YOURLS service is a broken image

### ISSUE THREAD

**Issue by z886** [joshp23/YOURLS-IQRCodes#30]
hi, 
  I created a second YOURLS service on the same server, but the QR code generated by the IQRCodes plugin of the second YOURLS service is a broken image?
Thank you!

**Comment by joshp23** [comment]
that's very little information to go on. is there any information in your logs? what differences are there between the two setups?

permissions is a good place to start. also, for some reason copying files to `/pages` directory sometimes fixes when they are merely symlinked.

**Comment by joshp23** [comment]
Also, did you look through closed issue que? the complaint of broken image is covered there in depth
