### ISSUE TITLE
iqrcodes.js does not respect options for file formats

### ISSUE THREAD

**Issue by serotonincrash** [joshp23/YOURLS-IQRCodes#34]
In line 28 of iqrcodes.js:

`var fn = 'qrc_' + md5(shorturl) + '.png';`

does not actually respect the file format that is given in the options and is hardcoded to png.

Possibly related to #33 as a reason why SVGs are not being generated properly.

**Comment by serotonincrash** [comment]
This can be fixed by editing the appended HTML to use the php .qr implementation that serves the proper file.

`var insertimg = "<div id='qrcode' class='share'><h3>QR Code</h3><img id='myid' src='" + shorturl + ".qr" + "' /></div>";`

**Comment by joshp23** [comment]
I utilized a solution that I had begun and drifted away from. Thank you for bringing this back to my attention.
