### ISSUE TITLE
Missing QR-Codes with yourls 1.7.9

### ISSUE THREAD

**Issue by Andyt8** [joshp23/YOURLS-IQRCodes#36]
Hello,

I have a strange behavior with yourls 1.7.9 and enabled iqrcodes + usrv. Before the upgrade I see qr code for short urls. After that, it stopped working. It looks like, I don't get the picture - the generation is still working.

According to my own search, it looks like, yourls changed the position of the folder "pages". In the new version, the folder "pages" is located under the folder "user". Before that it was located at the base folder.

If I copy the files from the old folder to the new folder it start working. However, I'm not able to remove the old folder, because it will stop to work. At the moment the files need to be in both folders. So it looks like, iqrcodes, usrv or both need an update for that?

regards, Andyt

**Comment by joshp23** [comment]
fixed with 2.2.0

**Comment by Andyt8** [comment]
Thanks - working perfect.
