### ISSUE TITLE
QR code not shown when Yourls installed in subfolder

### ISSUE THREAD

**Issue by phalox** [joshp23/YOURLS-IQRCodes#39]
When yourls is installed in a subfolder, like:
your.ls/s/

the QR code is not displayed:
![image](https://user-images.githubusercontent.com/3983738/83977427-c0ebe280-a900-11ea-9ef4-ec190dcab6aa.png)
Because the underlying URL is 
https://your.ls/srv/ and not https://your.ls/s/srv/.

**Comment by phalox** [comment]
Fixed here:
#38

**Comment by joshp23** [comment]
merged. thank you
