### ISSUE TITLE
Set permissions

### ISSUE THREAD

**Issue by ghost** [joshp23/YOURLS-IQRCodes#4]
Hello,

in the readme is "2. Set permissions" but which files and permissions do I need to change?
I get an error "empty string".

Thanks
Manuel

**Comment by joshp23** [comment]
you have to chmod/chown ([info](https://www.linux.com/learn/understanding-linux-file-permissions)) the plugin directory to be readable by the webserver, and whatever folder you use for the cache to be writable.

**Comment by ghost** [comment]
Thanks. Wasn't a permisson problem.
Missed the line "move file to YOURLS/pages/" in assets/srv.php

**Comment by joshp23** [comment]
I'll update the readme
