### ISSUE TITLE
Max image size limited to "10"

### ISSUE THREAD

**Issue by phalox** [joshp23/YOURLS-IQRCodes#40]
Hi there,

I was wondering why the max image size is limited to 10?
![image](https://user-images.githubusercontent.com/3983738/83977801-89cb0080-a903-11ea-9fdc-f9eff5936eab.png)
I've hardcoded 100 here (in stead of 10) here:
https://github.com/joshp23/YOURLS-IQRCodes/blob/ff1de51fbd59761e2a96811ed392411bba8b8e79/iqrcodes/plugin.php#L174
and it worked just fine. Performance concerns?

**Comment by joshp23** [comment]
I'm sure I had some reason, not certain what. I see no problem opening this up.

**Comment by joshp23** [comment]
https://github.com/joshp23/YOURLS-IQRCodes/commit/9750ddd8611e6ea2f5a71f6fd235831059627350
