### ISSUE TITLE
Possible configuration issue with U-SRV/IQRCodes

### ISSUE THREAD

**Issue by DaniBedz** [joshp23/YOURLS-IQRCodes#41]
Hi there,

I'm having some trouble with U-SRV/IQRCodes - not sure which is causing the issue here, or if it's something with the configuration on my server. 

When I upload a file, for example setting the logo file in IQRCodes, the image displays as broken, and if I right-click "View Image", the message I get is:

FAIL: missing passkey

Taking a look at the URL, it looks like there's a key associated with the image:
https://bedz.me/srv/?id=iqrcodes&key=b913e6992d8288d769986ad013a0a19b&fn=logo.png

Is there any way of checking what the key for an image should be when uploading a logo for example? 

The images/qr codes are uploaded to the correct cache folders on the server and I can view them directly on there, but it would seem that retrieving them via /srv/ keeps throwing the above error.

I've tried this in Firefox, Chrome and Safari with the same results.

**My current configuration is:**
YOURLS v 1.7.9
YOURLS-IQRCodes v 2.2.1
YOURLS-U-SRV v 2.3.3
Server = nginx
PHP v7.4.3
MariaDB v10.4.14

I disabled all other plugins (such as Sleeky) to eliminate that as a possibility also.

Files qrchk.php & srv.php copied into:
/user/pages

U-SRV: SRV.php: Success: installed and up to date.
IQR-Codes: Plugin: Success: U-SRV is installed and enabled.
srv.php status: Success: installed and up to date.

**Permissions:**
YOURLS_CACHE /fu and /qr all 777.
Codes showing in /qr.
/fu

/pages 755
/pages/qrchk.php 644
/pages/srv.php 755

The same permissions on the same files in /user/pages and /plugins/iqrcodes/assets.
Cache folder in /plugins/iqrcodes set to 777.

Have you seen anything like this before? I spent most of yesterday trying different things, but I always end up at the same point with this error. Any possible suggestions of things to try would be much appreciated!

**Comment by joshp23** [comment]
One of the expected results of U-SRV is anti-hot-linking. So, you shouldn't be able to right-click->view image anyway. However, the expected result is `FAIL: bad access key`. In your example, there is certainly a key there in the query string, and so that is odd.

Do QR Codes display without the logo?

When you experience this error, what do your logs say?

**Comment by joshp23** [comment]
dead issue
