### ISSUE TITLE
qr code in db

### ISSUE THREAD

**Issue by owldrak** [joshp23/YOURLS-IQRCodes#42]
hey,

is it possible to save QR codes into DB binded to URLs? So they can be used elsewhere and not only share boxes. thanks

**Comment by joshp23** [comment]
Probably a no on the database as there are already several ways to retrieve QR codes without a database. A few examples can be found by looking at the `Display Examples` tab in the plugin's admin page in your YOURLS installation. 

Other examples are in the code, for instance, you can find the filename and path with relative ease using something like the following:
https://github.com/joshp23/YOURLS-IQRCodes/blob/9750ddd8611e6ea2f5a71f6fd235831059627350/iqrcodes/plugin.php#L553-L557
I don't recommend that, but it's possible. 

You can also find an example of how to link a QR code into a Wordpress widget linked to in the README.  Should be plenty of inspiration there.
