### ISSUE TITLE
EPS export

### ISSUE THREAD

**Issue by ghost** [joshp23/YOURLS-IQRCodes#5]
I've found some lines of code with EPS in phpqrcode. Is it possible to activate this in the plugin?

**Comment by djcesar** [comment]
+1 Please allow EPS or PDF

**Comment by joshp23** [comment]
It seems to me that this would require external libraries to generate these files, and this would add quite a bit of bulk to this project (increase of over 3000%), which I'm not really excited about. 

So, I'm closing this unless someone can show me that it won't add a ridiculous amount of bloat.
