### ISSUE TITLE
Missing function snapshot_cache_mkdir (using latest YOURLS Version)

### ISSUE THREAD

**Issue by wackerm** [joshp23/YOURLS-IQRCodes#7]
YOURLS Version (latest master, 1.7.1), PHP 7.0

If you change the `Image Cache Location` in the plugin administration the following error arises:

Error Message:
`Fatal error: Uncaught Error: Call to undefined function snapshot_cache_mkdir() in /var/www/yourls/user/plugins/iqrcodes/plugin.php:493`

**Comment by wackerm** [comment]
**Solution:** 
Change in file plugin.php on line 493:
`snapshot_cache_mkdir($new);`
to:
`iqrcodes_mkdir($new);`

**Comment by joshp23** [comment]
good eye here, thanks
